repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: no-commit-to-branch
        args: ["--branch", "master"]
      - id: pretty-format-json
        args: ["--autofix"]

  - repo: https://github.com/myint/autoflake
    rev: v1.5.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --ignore-init-module-imports

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        entry: flake8
        additional_dependencies:
          [
            flake8-bugbear,
            flake8-builtins,
            pep8-naming,
            flake8-commas,
            flake8-functions-names,
            flake8-length,
            flake8-quotes,
            flake8-variables-names,
            flake8_simplify,
            flake8-isort,
          ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/myint/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
        args: [--in-place]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        files: \.(json|yml|yaml)$
        args: ["--write"]
