version: "3.8"

services:
  postgresdb:
    image: postgres:15.4-alpine3.18
    container_name: fastapi-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - database

  pgadmin:
    image: dpage/pgadmin4
    container_name: fastapi-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      - .env
    networks:
      - database
    depends_on:
      - postgresdb

volumes:
  postgres_data:
    name: "postgres-fastapi"
  pgadmin_data:
    name: "pgadmin-fastapi"

networks:
  database:
    driver: bridge
    name: "database_network"
